class_name Enums extends Node

enum RoomType {SPAWN, TRAP, THRONE, SHOP, BOSS, ITEM, EVENT, SURVIVE}

enum StatModifyerType {ADD, MULTIPLY, OVERRIDE}

enum ItemProcs {PRE_PLAYER_HIT, POST_PLAYER_HIT, PRE_ENEMY_HIT, POST_ENEMY_HIT, ENEMY_DEATH, PICKUP, ROOM_LOAD}

enum DamageSource {AUTO_ATTACK, BURN, POISON, ITEM, AOE, CONTACT, MELEE, RANGED}
